import { ArrowLeft, ArrowRight, Building2, Leaf, ShieldCheck, Sprout } from 'lucide-react'
import { Button } from '../components/ui'

const roles = [
  { id: 'farmer', title: 'Farmer', copy: 'Discover markets and find the right buyer.', icon: Sprout },
  { id: 'buyer', title: 'Buyer', copy: 'Source quality produce with confidence.', icon: Building2 },
  { id: 'admin', title: 'Admin', copy: 'Manage verification and platform activity.', icon: ShieldCheck },
]

export default function LoginPage({ login, navigate }) {
  const [selected, setSelected] = React.useState('farmer')
  const selectedRole = roles.find(role => role.id === selected)
  return <div className="grid min-h-screen bg-[#f7faf7] lg:grid-cols-[.85fr_1.15fr]"><aside className="hidden bg-[#103e2b] p-12 text-white lg:flex lg:flex-col"><button onClick={() => navigate('landing')} className="flex items-center gap-2 text-left"><span className="flex h-10 w-10 items-center justify-center rounded-xl bg-white/10 text-[#bdeccc]"><Leaf size={21} fill="currentColor" /></span><span className="font-[Manrope] text-xl font-extrabold">KrishiLink</span></button><div className="my-auto max-w-sm"><p className="text-xs font-bold uppercase tracking-[.16em] text-[#98d7b0]">Demo workspace</p><h1 className="mt-4 text-4xl font-extrabold leading-tight tracking-tight">Better selling starts with better information.</h1><p className="mt-5 leading-relaxed text-white/65">Explore how market intelligence, verified buyers and transparent logistics come together in one farmer-first workflow.</p></div><p className="text-xs font-semibold text-white/40">Right Price. Right Buyer. Right Time.</p></aside><main className="flex items-center justify-center p-5 sm:p-10"><div className="w-full max-w-xl"><button onClick={() => navigate('landing')} className="mb-10 flex items-center gap-2 text-sm font-bold text-slate-500 hover:text-forest-700"><ArrowLeft size={17} />Back to home</button><div className="mb-8"><p className="text-xs font-bold uppercase tracking-[.14em] text-forest-600">Welcome to KrishiLink</p><h2 className="mt-2 text-3xl font-extrabold tracking-tight text-ink">Choose your demo role</h2><p className="mt-2 text-sm text-slate-500">No password required — this is a hackathon prototype.</p></div><div className="space-y-3">{roles.map(role => { const Icon = role.icon; const active = role.id === selected; return <button key={role.id} onClick={() => setSelected(role.id)} className={`flex w-full items-center gap-4 rounded-2xl border p-4 text-left transition ${active ? 'border-forest-500 bg-forest-50 shadow-sm' : 'border-slate-200 bg-white hover:border-forest-200'}`}><span className={`flex h-11 w-11 items-center justify-center rounded-xl ${active ? 'bg-forest-600 text-white' : 'bg-slate-100 text-slate-500'}`}><Icon size={21} /></span><span className="flex-1"><span className="block font-extrabold text-ink">{role.title}</span><span className="mt-0.5 block text-sm text-slate-500">{role.copy}</span></span><span className={`h-5 w-5 rounded-full border-2 ${active ? 'border-forest-600 bg-forest-600 shadow-[inset_0_0_0_3px_#effaf3]' : 'border-slate-300'}`} /></button> })}</div><Button onClick={() => login(selected)} icon={ArrowRight} iconRight className="mt-7 w-full py-3.5">Continue as {selectedRole.title}</Button><p className="mt-5 text-center text-xs text-slate-400">Demo data is fictional and used only for presentation.</p></div></main></div>
}

import React from 'react'
